# Site settings
author: cailee
title: 
header-img: img/home-bg.png
email: cailee.adamson+osebblogsetup01@wework.com
copyright_name: cailee
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  caileetest01

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
